# Dependencies
gems:                [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               R Programming
tagline:             ''
description:         '<img src="https://www.r-project.org/Rlogo.png" height=60 </img> forked from <a href="https://github.com/uc-r/uc-r.github.io/">uc-r.github.io</a> <href="http://uc-r.github.io/">http://uc-r.github.io/</a>'
url:                 https://www.r-project.org/
baseurl:             ''

